### ISSUE TITLE
Figure SHH connection problem for gizmo

### ISSUE THREAD

**Issue by rvizarreta** [rvizarreta/Mx2_SlowControlsDisplay#16]

**Comment by rvizarreta** [comment]
Keep getting ssh connection errors:

```
Exporting environment variables
TESTDIR=/home/acd/acdemo/gizmo-control
DAQEXECPATH=/home/acd/acdemo/gizmo-control/gizmo
Start Date and Time is: 2023-07-24 19:19:40
Executing /home/acd/acdemo/gizmo-control/gizmo/gizmo_write.py -d False
Traceback (most recent call last):
  File "/home/acd/acdemo/usr/vanessa/py3/lib64/python3.6/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/acd/acdemo/usr/vanessa/py3/lib64/python3.6/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/acd/acdemo/usr/vanessa/py3/lib64/python3.6/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/acd/acdemo/usr/vanessa/py3/lib64/python3.6/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/acd/acdemo/usr/vanessa/py3/lib64/python3.6/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/acd/acdemo/usr/vanessa/py3/lib64/python3.6/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib64/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/home/acd/acdemo/usr/vanessa/py3/lib64/python3.6/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/acd/acdemo/usr/vanessa/py3/lib64/python3.6/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fd8e87f49e8>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/acd/acdemo/usr/vanessa/py3/lib64/python3.6/site-packages/requests/adapters.py", line 450, in send
    timeout=timeout
  File "/home/acd/acdemo/usr/vanessa/py3/lib64/python3.6/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/acd/acdemo/usr/vanessa/py3/lib64/python3.6/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8086): Max retries exceeded with url: /query?q=CREATE+DATABASE+%22gizmo%22&db=gizmo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8e87f49e8>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/acd/acdemo/gizmo-control/gizmo/gizmo_write.py", line 161, in <module>
    main(debug = args.d)
  File "/home/acd/acdemo/gizmo-control/gizmo/gizmo_write.py", line 47, in main
    client_db.create_database('gizmo')
  File "/home/acd/acdemo/usr/vanessa/py3/lib64/python3.6/site-packages/influxdb/client.py", line 747, in create_database
    method="POST")
  File "/home/acd/acdemo/usr/vanessa/py3/lib64/python3.6/site-packages/influxdb/client.py", line 527, in query
    expected_response_code=expected_response_code
  File "/home/acd/acdemo/usr/vanessa/py3/lib64/python3.6/site-packages/influxdb/client.py", line 342, in request
    timeout=self._timeout
  File "/home/acd/acdemo/usr/vanessa/py3/lib64/python3.6/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/acd/acdemo/usr/vanessa/py3/lib64/python3.6/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/acd/acdemo/usr/vanessa/py3/lib64/python3.6/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8086): Max retries exceeded with url: /query?q=CREATE+DATABASE+%22gizmo%22&db=gizmo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd8e87f49e8>: Failed to establish a new connection: [Errno 111] Connection refused',))
End Date and Time is: 2023-07-24 19:19:42
```

**Comment by rvizarreta** [comment]
Turning it off and the on fixed the issue
